Repository CarlosGLOZ/Proyecto-1, pull requests merged in 2022-11, with the labels that each got.

#6 login.php
  static/css/login.css
  static/img/imgerror.png
  static/js/function_login.js
  static/js/validacion-login.js
  view/login.php
Labels: front-end

#7 Carlos
  controller/index_controller.php
  controller/login_controller.php
  proc/func.php
  view/index.php
  view/login.php
Labels: back-end

#8 Carlos
  .gitignore
  bd/bd.sql
  bd/bd_restaurante.sql
  config/config.php
  controller/index_controller.php
  view/index.php
Labels: back-end

#9 Carlos
  config/config.php
  controller/index_controller.php
  proc/func.php
  proc/login_proc.php
  static/img/test
  view/login.php
Labels: back-end

#17 mostrar.php
  static/css/login.css
  static/css/mostrar.css
  static/img/imgexcla.png
  static/img/logores.png
  static/js/function_logout.js
  view/login.php
  view/logout.php
  view/mostrar.php
Labels: front-end

#19 Carlos
  config/config.php
  controller/index_controller.php
  controller/registros_controller.php
  models/mesa.php
  proc/cambiar_estado_mesa.php
  proc/cerrar_sesion.php
  proc/func.php
  proc/login_proc.php
  static/js/index.js
  view/index.php
  view/registros.php
Labels: back-end

#20 Mario
  controller/index_controller.php
  proc/login_proc.php
  static/css/mostrar.css
  static/img/mesa-10.2.PNG
  static/img/mesa-2.2.PNG
  static/img/mesa-4.2.PNG
  static/img/mesa-6.2.PNG
  static/img/mesa-8.2.PNG
  static/img/mesa10-rojo.PNG
  static/img/mesa10-verde.PNG
  static/img/mesa2-rojo.PNG
  static/img/mesa2-verde.PNG
  static/img/mesa4-rojo.PNG
  static/img/mesa4-verde.PNG
  static/img/mesa6-rojo.PNG
  static/img/mesa6-verde.PNG
  static/img/mesa8-rojo.PNG
  static/img/mesa8-verde.PNG
  static/js/function_login.js
  static/js/function_logout.js
  static/js/validacion-login.js
  view/login.php
  view/mostrar.php
Labels: front-end

#21 filtro mesas ok
  config/config.php
  controller/index_controller.php
  models/mesa.php
  view/index.php
  view/mostrar.php
Labels: back-end

#26 Carlos
  bd/bd_restaurante.sql
  config/config.php
  controller/index_controller.php
  controller/registros_controller.php
  models/mesa.php
  proc/cambiar_estado_mesa.php
  proc/func.php
  static/css/filtros.css
  static/css/filtros.less
  static/css/index.css
  static/css/modal_mesas.css
  static/css/modal_mesas.less
  static/css/mostrar.css
  static/css/registro.css
  static/css/registro.less
  static/img/mesa-10-blanco.PNG
  static/img/mesa-10-rojo.PNG
  static/img/mesa-10-verde.PNG
  static/img/mesa-2-blanco.PNG
  static/img/mesa-2-rojo.PNG
  static/img/mesa-2-verde.PNG
  static/img/mesa-4-blanco.PNG
  static/img/mesa-4-rojo.PNG
  static/img/mesa-4-verde.PNG
  static/img/mesa-6-blanco.PNG
  static/img/mesa-6-rojo.PNG
  static/img/mesa-6-verde.PNG
  static/img/mesa-8-blanco.PNG
  static/img/mesa-8-rojo.PNG
  static/img/mesa-8-verde.PNG
  static/js/filtros.js
  static/js/function_logout.js
  static/js/modales_mesas.js
  static/js/styles.js
  view/index.php
  view/registro.php
  view/registros.php
Labels: front-end, back-end

#27 arreglos filtros
  controller/index_controller.php
  models/mesa.php
  view/index.php
Labels: back-end

#28 filtros genericos
  controller/registros_controller.php
  proc/func.php
  view/registro.php
Labels: back-end

#29 Sergi
  README.md
Labels: documentation

#30 Carlos
  2223_DAW2_PROYECTO_1_GiraldoCarlos_SergiGarcia_MarioGomez.zip
  proc/cambiar_estado_mesa.php
  proc/login_proc.php
Labels: back-end

#31 escape
  2223_DAW2_PROYECTO_1_GiraldoCarlos_SergiGarcia_MarioGomez.zip
  bd/bd_restaurante.sql
  proc/login_proc.php
Labels: back-end

#32 arreglo login
  2223_DAW2_PROYECTO_1_GiraldoCarlos_SergiGarcia_MarioGomez.zip
  proc/login_proc.php
Labels: back-end
